# Generated by Django 5.2.4 on 2025-07-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userproofupload",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
