# Generated by Django 5.2.4 on 2025-07-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_alter_userprogress_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
    ]
